# Generated by Django 4.0.3 on 2022-03-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='typeBike',
            new_name='type_bike',
        ),
    ]
