# Generated by Django 4.0.3 on 2022-03-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_rename_typebike_bike_type_bike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeBike',
            new_name='BikeType',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='type_bike',
            new_name='bike_type',
        ),
    ]
