# Generated by Django 4.0.3 on 2022-03-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_alter_bike_bike_type_alter_bike_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bikes.biketype'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.manufacturer'),
        ),
    ]
